# Generated by Django 3.2.6 on 2021-10-19 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='question',
            field=models.TextField(verbose_name='Вопрос и его детали'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Название вопроса'),
        ),
    ]
