# Generated by Django 3.2.6 on 2021-10-17 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='Описание Вопроса'),
        ),
        migrations.AlterField(
            model_name='post',
            name='question',
            field=models.CharField(max_length=400),
        ),
    ]
