# Generated by Django 3.2.6 on 2021-10-19 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_auto_20211019_1026'),
        ('questions', '0005_auto_20211018_1907'),
    ]

    operations = [
    ]
