# Generated by Django 3.2.6 on 2021-10-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='lesson_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='clip-reading-books.png', upload_to='course_pics'),
        ),
    ]
