# Generated by Django 3.2.6 on 2021-10-21 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='clip-reading-books.png', upload_to='course_pics')),
                ('lesson_cost', models.IntegerField()),
                ('date_lesson', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.CharField(max_length=20)),
                ('lesson_type', models.CharField(choices=[('1', 'Mono'), ('2', 'Regular')], default='1', max_length=100)),
                ('lesson_url', models.URLField()),
                ('max_student', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_author', to=settings.AUTH_USER_MODEL)),
                ('students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applied_students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='coursedirection',
            name='keywords',
            field=models.ManyToManyField(to='dashboard.CourseKeywords'),
        ),
        migrations.DeleteModel(
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.coursedirection'),
        ),
    ]
