# Generated by Django 3.2.6 on 2021-10-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_courses_lesson_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(default='clip-reading-books.png', upload_to='course_pics'),
        ),
    ]
