# Generated by Django 3.2.6 on 2021-10-21 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_auto_20211021_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='applied_students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursedirection',
            name='keywords',
            field=models.ManyToManyField(to='dashboard.CourseKeywords'),
        ),
    ]
