# Generated by Django 3.2.6 on 2021-10-21 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20211021_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='key',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursedirection',
            name='keywords',
            field=models.ManyToManyField(to='dashboard.CourseKeywords'),
        ),
    ]
