# Generated by Django 3.2.6 on 2021-10-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20211022_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='key',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coursedirection',
            name='keywords',
            field=models.ManyToManyField(to='dashboard.CourseKeywords'),
        ),
    ]
