# Generated by Django 3.2.6 on 2021-10-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_coursedirection_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='report_by_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='coursedirection',
            name='keywords',
            field=models.ManyToManyField(to='dashboard.CourseKeywords'),
        ),
    ]
