# Generated by Django 3.2.6 on 2021-11-23 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20211026_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedirection',
            name='keywords',
            field=models.ManyToManyField(to='dashboard.CourseKeywords'),
        ),
    ]
